#!/bin/bash
#
# DietPi's SSH server doesn't support `scp`, so use `tar` instead.

set -e
cd "$(readlink -f $(dirname "${BASH_SOURCE[0]}"))"

if [ -z "$1" ]
then
    echo usage: push HOSTNAME
    exit 2
fi

for hostname in "$@"
do
    tar cf - crontab recorder.py requirements.txt |
        ssh $hostname tar xvf -
done
